### ISSUE TITLE
Actividad 4 Infografia de libreria

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-MarcoRg06#1]
Hecho por: Marco Uriel Rosas Garcia.
[Infografia_Marco Uriel Rosas Garcia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-MarcoRg06/files/14566235/Infografia_Marco.Uriel.Rosas.Garcia.pdf)

**Comment by Nancy-0714** [comment]
Calificación 18, faltan las fuentes bibliografícas.

**Comment by josealfredo79** [comment]
Revisado...
